
-- ************************************************************************
-- NAME : LOCALIZATION CONSTANTS for TITAN GOLD TRACKER
-- ************************************************************************

TITAN_GOLDTRACKER_TOOLTIPTEXT= "Total Gold on";
TITAN_GOLDTRACKER_ITEMNAME = "Gold Tracker";
TITAN_GOLDTRACKER_TEXT = "Gold Tracker";
TITAN_GOLDTRACKER_LOADED = "loaded";
TITAN_GOLDTRACKER_CLEAR_DATA_TEXT = "Clear Database";
TITAN_GOLDTRACKER_RESET_SESS_TEXT = "Reset Current Session";
TITAN_GOLDTRACKER_DB_CLEARED = "Titan Gold Tracker - Database cleared.";
TITAN_GOLDTRACKER_SESSION_RESET = "Titan Gold Tracker - Session reset.";
TITAN_GOLDTRACKER_MENU_TEXT = TITAN_GOLDTRACKER_ITEMNAME;
TITAN_GOLDTRACKER_TOOLTIP = "Gold Info";
TITAN_GOLDTRACKER_TOGGLE_PLAYER_TEXT = "Display player gold";
TITAN_GOLDTRACKER_TOGGLE_ALL_TEXT = "Display server gold";
TITAN_GOLDTRACKER_SESS_EARNED = "Earned this session";
TITAN_GOLDTRACKER_PERHOUR_EARNED = "Earned per hour";
TITAN_GOLDTRACKER_SESS_LOST = "Lost this session";
TITAN_GOLDTRACKER_PERHOUR_LOST = "Lost per hour";
TITAN_GOLDTRACKER_STATS_TITLE = "Session Statistics";
TITAN_GOLDTRACKER_TTL_GOLD = "Total Gold";
TITAN_GOLDTRACKER_START_GOLD = "Starting Gold";
TITAN_GOLDTRACKER_TOGGLE_SORT_GOLD = "Sort table by gold";
TITAN_GOLDTRACKER_TOGGLE_SORT_NAME = "Sort table by name";
TITAN_GOLDTRACKER_TOGGLE_GPH_SHOW = "Display gold per hour";
TITAN_GOLDTRACKER_TOGGLE_GPH_HIDE = "Hide gold per hour";

TITAN_GOLDTRACKER_TOGGLE_PLAYER_SHOW = "Make this toon visible";
TITAN_GOLDTRACKER_TOGGLE_PLAYER_HIDE = "Hide this toon";
TITAN_GOLDTRACKER_STATUS_PLAYER_SHOW = "visible";
TITAN_GOLDTRACKER_STATUS_PLAYER_HIDE = "hidden";

-- GERMAN LOCALIZATION THANKS TO OMEGASNOW; UPDATED BY SENSITY.

if ( GetLocale() == "deDE" ) then
	TITAN_GOLDTRACKER_TOOLTIPTEXT= "Gesamtes Gold auf";
	TITAN_GOLDTRACKER_ITEMNAME = "Gold Tracker";
	TITAN_GOLDTRACKER_TEXT = "Gold Tracker";
	TITAN_GOLDTRACKER_LOADED = "geladen";
	TITAN_GOLDTRACKER_CLEAR_DATA_TEXT = "L\195\182sche Datenbank";
	TITAN_GOLDTRACKER_RESET_SESS_TEXT = "Sitzung zur\195\188cksetzen";
	TITAN_GOLDTRACKER_DB_CLEARED = "Titan Gold Tracker - Datenbank gel\195\182scht.";
	TITAN_GOLDTRACKER_SESSION_RESET = "Titan Gold Tracker - Sitzung zur\195\188ck gesetzt.";
	TITAN_GOLDTRACKER_MENU_TEXT = TITAN_GOLDTRACKER_ITEMNAME;
	TITAN_GOLDTRACKER_TOOLTIP = TITAN_GOLDTRACKER_TEXT;
	TITAN_GOLDTRACKER_TOGGLE_PLAYER_TEXT = "Zeige Spieler Gold";
	TITAN_GOLDTRACKER_TOGGLE_ALL_TEXT = "Zeige Server Gold";
	TITAN_GOLDTRACKER_SESS_EARNED = "Eingenommen in der Sitzung";
	TITAN_GOLDTRACKER_PERHOUR_EARNED = "Eingenommen pro Stunde";
	TITAN_GOLDTRACKER_SESS_LOST = "Ausgegeben in der Sitzung";
	TITAN_GOLDTRACKER_PERHOUR_LOST = "Ausgegeben pro Stunde";
	TITAN_GOLDTRACKER_STATS_TITLE = "Sitzungsstatistik";
	TITAN_GOLDTRACKER_TTL_GOLD = "Gesamtes Gold";
	TITAN_GOLDTRACKER_START_GOLD = "Anf\195\164ngliches Gold";
	TITAN_GOLDTRACKER_TOGGLE_SORT_GOLD = "Sortiere Tabelle nach Gold";
	TITAN_GOLDTRACKER_TOGGLE_SORT_NAME = "Sortiere Tabelle nach Name";
	TITAN_GOLDTRACKER_TOGGLE_GPH_SHOW = "Zeige Gold pro Stunde";
	TITAN_GOLDTRACKER_TOGGLE_GPH_HIDE = "Verberge Gold pro Stunde";

	TITAN_GOLDTRACKER_TOGGLE_PLAYER_SHOW = "Diesen Spieler anzeigen";
	TITAN_GOLDTRACKER_TOGGLE_PLAYER_HIDE = "Diesen Spieler verbergen";
	TITAN_GOLDTRACKER_STATUS_PLAYER_SHOW = "Sichtbar";
	TITAN_GOLDTRACKER_STATUS_PLAYER_HIDE = "Verborgen";
end

-- FRENCH LOCALIZATION THANKS TO WILF - LES CHEVALIERS POURPRES - VOL'JIN; UPDATED BY OXID_FOX.

if ( GetLocale() == "frFR" ) then
	TITAN_GOLDTRACKER_TOOLTIPTEXT= "Or total sur";
	TITAN_GOLDTRACKER_ITEMNAME = "Gold Tracker";
	TITAN_GOLDTRACKER_TEXT = "Gold Tracker";
	TITAN_GOLDTRACKER_LOADED = "charg\195\169";
	TITAN_GOLDTRACKER_CLEAR_DATA_TEXT = "Vider la base de donn\195\169es";
	TITAN_GOLDTRACKER_RESET_SESS_TEXT = "Remise \195\160 z\195\169ro de la session";
	TITAN_GOLDTRACKER_DB_CLEARED = "Titan Gold Tracker - Base vid\195\169e.";
	TITAN_GOLDTRACKER_SESSION_RESET = "Titan Gold Tracker - Session remise \195\160 z\195\169ro.";
	TITAN_GOLDTRACKER_MENU_TEXT = TITAN_GOLDTRACKER_ITEMNAME;
	TITAN_GOLDTRACKER_TOOLTIP = "Infos sur l'or";
	TITAN_GOLDTRACKER_TOGGLE_PLAYER_TEXT = "Afficher l'or du joueur";
	TITAN_GOLDTRACKER_TOGGLE_ALL_TEXT = "Afficher l'or sur le serveur";
	TITAN_GOLDTRACKER_SESS_EARNED = "Gagn\195\169 cette session";
	TITAN_GOLDTRACKER_PERHOUR_EARNED = "Gagn\195\169 par heure";
	TITAN_GOLDTRACKER_SESS_LOST = "Perdu cette session";
	TITAN_GOLDTRACKER_PERHOUR_LOST = "Perdu par heure";
	TITAN_GOLDTRACKER_STATS_TITLE = "Statistiques de la session";
	TITAN_GOLDTRACKER_TTL_GOLD = "Or Total";
	TITAN_GOLDTRACKER_START_GOLD = "Or de d\195\169part";
	TITAN_GOLDTRACKER_TOGGLE_SORT_GOLD = "Trier par or";
	TITAN_GOLDTRACKER_TOGGLE_SORT_NAME = "Trier par nom";
	TITAN_GOLDTRACKER_TOGGLE_GPH_SHOW = "Afficher l'or gagn\195\169 par heure";
	TITAN_GOLDTRACKER_TOGGLE_GPH_HIDE = "Cacher l'or gagn\195\169 par heure";

	TITAN_GOLDTRACKER_TOGGLE_PLAYER_SHOW = "Afficher ce personnage";
	TITAN_GOLDTRACKER_TOGGLE_PLAYER_HIDE = "Cacher ce personnage";
	TITAN_GOLDTRACKER_STATUS_PLAYER_SHOW = "visible";
	TITAN_GOLDTRACKER_STATUS_PLAYER_HIDE = "cach\195\169";
end

-- SPANISH LOCALIZATION THANKS TO RHODIUM 

if ( GetLocale() == "esES" ) then
	TITAN_GOLDTRACKER_TOOLTIPTEXT= "Oro total en";
	TITAN_GOLDTRACKER_ITEMNAME = "Gold Tracker";
	TITAN_GOLDTRACKER_TEXT = "Gold Tracker";
	TITAN_GOLDTRACKER_LOADED = "Cargado";
	TITAN_GOLDTRACKER_CLEAR_DATA_TEXT = "Limpiar Base de Datos";
	TITAN_GOLDTRACKER_RESET_SESS_TEXT = "Resetear Sesion Actual";
	TITAN_GOLDTRACKER_DB_CLEARED = "Titan Gold Tracker - Base de Datos limpiada.";
	TITAN_GOLDTRACKER_SESSION_RESET = "Titan Gold Tracker - Sesion reiniciada.";
	TITAN_GOLDTRACKER_MENU_TEXT = TITAN_GOLDTRACKER_ITEMNAME;
	TITAN_GOLDTRACKER_TOOLTIP = TITAN_GOLDTRACKER_TEXT;
	TITAN_GOLDTRACKER_TOGGLE_PLAYER_TEXT = "Mostrar oro del jugador";
	TITAN_GOLDTRACKER_TOGGLE_ALL_TEXT = "Mostrar oro en el server";
	TITAN_GOLDTRACKER_SESS_EARNED = "Ganado esta sesion";
	TITAN_GOLDTRACKER_PERHOUR_EARNED = "Ganado por hora";
	TITAN_GOLDTRACKER_SESS_LOST = "Perdido esta sesion";
	TITAN_GOLDTRACKER_PERHOUR_LOST = "Perdido por hora";
	TITAN_GOLDTRACKER_STATS_TITLE = "Estadisticas de esta sesion";
	TITAN_GOLDTRACKER_TTL_GOLD = "Oro Total";
	TITAN_GOLDTRACKER_START_GOLD = "Oro al principio";
	TITAN_GOLDTRACKER_TOGGLE_SORT_GOLD = "Ordenar tabla por Oro";
	TITAN_GOLDTRACKER_TOGGLE_SORT_NAME = "Ordenar tabla por nombre";
	TITAN_GOLDTRACKER_TOGGLE_GPH_SHOW = "Mostrar oro por hora";
	TITAN_GOLDTRACKER_TOGGLE_GPH_HIDE = "Ocultar oro por hora";

	TITAN_GOLDTRACKER_TOGGLE_PLAYER_SHOW = "Hacer este personaje visible";
	TITAN_GOLDTRACKER_TOGGLE_PLAYER_HIDE = "Ocultar este personaje";
	TITAN_GOLDTRACKER_STATUS_PLAYER_SHOW = "visible";
	TITAN_GOLDTRACKER_STATUS_PLAYER_HIDE = "oculto";
end

-- RUSSIAN LOCALIZATION THANKS TO STINGERSOFT
if ( GetLocale() == "ruRU" ) then
	TITAN_GOLDTRACKER_TOOLTIPTEXT= "Всего золота";
	TITAN_GOLDTRACKER_ITEMNAME = "Слежение за Золотом";
	TITAN_GOLDTRACKER_TEXT = "Титан: Слежение за Золотом";
	TITAN_GOLDTRACKER_LOADED = "загружен";
	TITAN_GOLDTRACKER_CLEAR_DATA_TEXT = "Очистить базу данных";
	TITAN_GOLDTRACKER_RESET_SESS_TEXT = "Сбросить текущий сеанс";
	TITAN_GOLDTRACKER_DB_CLEARED = "Титан: Слежение за Золотом - База данных очищена.";
	TITAN_GOLDTRACKER_SESSION_RESET = "Титан: Слежение за Золотом - Сеан сброшен.";
	TITAN_GOLDTRACKER_MENU_TEXT = TITAN_GOLDTRACKER_ITEMNAME;
	TITAN_GOLDTRACKER_TOOLTIP = TITAN_GOLDTRACKER_TEXT;
	TITAN_GOLDTRACKER_TOGGLE_PLAYER_TEXT = "Отображать золото у игрока";
	TITAN_GOLDTRACKER_TOGGLE_ALL_TEXT = "Отображать золото на сервера";
	TITAN_GOLDTRACKER_SESS_EARNED = "Заработано за данный сеанс";
	TITAN_GOLDTRACKER_PERHOUR_EARNED = "Заработано за час";
	TITAN_GOLDTRACKER_SESS_LOST = "Потрачено за данный сеанс";
	TITAN_GOLDTRACKER_PERHOUR_LOST = "Потрачено за час";
	TITAN_GOLDTRACKER_STATS_TITLE = "Статистика сеанса";
	TITAN_GOLDTRACKER_TTL_GOLD = "Всего золота";
	TITAN_GOLDTRACKER_START_GOLD = "Начальное количество золота";
	TITAN_GOLDTRACKER_TOGGLE_SORT_GOLD = "Сортировать по золоту";
	TITAN_GOLDTRACKER_TOGGLE_SORT_NAME = "Сортировать по имени";
	TITAN_GOLDTRACKER_TOGGLE_GPH_SHOW = "Отображать золото за час";
	TITAN_GOLDTRACKER_TOGGLE_GPH_HIDE = "Скрыть золота за час";

	TITAN_GOLDTRACKER_TOGGLE_PLAYER_SHOW = "Отображать данного персонажа";
	TITAN_GOLDTRACKER_TOGGLE_PLAYER_HIDE = "Скрыть данного персонажа";
	TITAN_GOLDTRACKER_STATUS_PLAYER_SHOW = "добавлен(а) в список отображаемых персонажей";
	TITAN_GOLDTRACKER_STATUS_PLAYER_HIDE = "убран(а) из списка отображаемых персонажей";
end
