function TitanLocalizeFR()
	TITAN_DEBUG = "<Titan>";
	TITAN_INFO = "<Titan>"

	TITAN_NA = "N/A";
	TITAN_SECONDS = "secondes";
	TITAN_MINUTES = "minutes";
	TITAN_HOURS = "heures";
	TITAN_DAYS = "jours";
	TITAN_SECONDS_ABBR = "s";
	TITAN_MINUTES_ABBR = "m";
	TITAN_HOURS_ABBR = "h";
	TITAN_DAYS_ABBR = "d";
	TITAN_MILLISECOND = "ms";
	TITAN_KILOBYTES_PER_SECOND = "Ko/s";
	TITAN_KILOBITS_PER_SECOND = "kbps"
	TITAN_MEGABYTE = "Mo";

	TITAN_MOVABLE_TOOLTIP = "Glisser pour d\195\169placer";

	TITAN_PANEL_ERROR_DUP_PLUGIN = " semble \195\170tre enregistr\195\169 plusieurs fois. Cela peut causer des probl\195\168mes \195\160 Titan Panel. Veuillez corriger le probl\195\168me."
	
	-- slash command help
	TITAN_PANEL_SLASH_STRING2 = LIGHTYELLOW_FONT_COLOR_CODE.."Utilisation: |cffffffff/tp {reset | reset tipfont/tipalpha/panelscale/spacing}";
	TITAN_PANEL_SLASH_STRING3 = " - "..LIGHTYELLOW_FONT_COLOR_CODE.."reset: | cffffffffR\195\169initialise les valeurs et positions du panneau.";
	TITAN_PANEL_SLASH_STRING4 = " - "..LIGHTYELLOW_FONT_COLOR_CODE.."reset tipfont: |cffffffffR\195\169initialise l'\195\169chelle des polices des tooltips.";
	TITAN_PANEL_SLASH_STRING5 = " - "..LIGHTYELLOW_FONT_COLOR_CODE.."reset tipalpha: |cffffffffR\195\169initialise la transparence des tooltips.";
	TITAN_PANEL_SLASH_STRING6 = " - "..LIGHTYELLOW_FONT_COLOR_CODE.."reset panelscale: |cffffffffR\195\169initialise l'\195\169chelle de Titan Panel.";
	TITAN_PANEL_SLASH_STRING7 = " - "..LIGHTYELLOW_FONT_COLOR_CODE.."reset spacing: |cffffffffR\195\169initialise Panel l'espacement des boutons.";
	TITAN_PANEL_SLASH_STRING8 = LIGHTYELLOW_FONT_COLOR_CODE.."Pour l'aide de BonusScanner, tapez : |cffffffff/bs"..LIGHTYELLOW_FONT_COLOR_CODE.." ou |cffffffff/bscan";
	
	-- slash command responses
	TITAN_PANEL_SLASH_RESP1 = LIGHTYELLOW_FONT_COLOR_CODE.."L'\195\169chelle des polices des tooltips de Titan Panel a \195\169t\195\169 r\195\169initialis\195\169e.";
	TITAN_PANEL_SLASH_RESP2 = LIGHTYELLOW_FONT_COLOR_CODE.."La transparence des tooltips de Titan Panel a \195\169t\195\169 r\195\169initialis\195\169e.";
	TITAN_PANEL_SLASH_RESP3 = LIGHTYELLOW_FONT_COLOR_CODE.."L'\195\169chelle de Titan Panel a \195\169t\195\169 r\195\169initialis\195\169e.";
	TITAN_PANEL_SLASH_RESP4 = LIGHTYELLOW_FONT_COLOR_CODE.."L'espacement des boutons de Titan Panel a \195\169t\195\169 r\195\169initialis\195\169.";
	
	TITAN_PANEL = "Titan Panel";
	TITAN_PANEL_REVISION = "Rev 799";
	TITAN_PANEL_VERSION_INFO = "|cffffffff par le "..RED_FONT_COLOR_CODE.."Titan Dev Team".." |cffffffff(HonorGoG, joejanko, Lothayer, Tristanian, oXidFoX, urnati & StingerSoft)";
	TITAN_PANEL_MENU_TITLE = "Titan Panel";
	TITAN_PANEL_MENU_HIDE = "Cacher";
	TITAN_PANEL_MENU_CUSTOMIZE = "Personnaliser";
	TITAN_PANEL_MENU_IN_COMBAT_LOCKDOWN = "(En Combat)";
	TITAN_PANEL_MENU_RELOADUI = "(Recharge l'interface)";
	TITAN_PANEL_MENU_SHOW_COLORED_TEXT = "Montre texte color\195\169";
	TITAN_PANEL_MENU_SHOW_ICON = "Montrer l'ic\195\180ne";
	TITAN_PANEL_MENU_SHOW_LABEL_TEXT = "Montrer le texte";
	TITAN_PANEL_MENU_AUTOHIDE = "Cacher auto";
	TITAN_PANEL_MENU_BGMINIMAP = "Minicarte du champ de bataille";
	TITAN_PANEL_MENU_CENTER_TEXT = "Centrer le texte";
	TITAN_PANEL_MENU_DISPLAY_ONTOP = "Afficher en haut";
	TITAN_PANEL_MENU_DISPLAY_BOTH = "Montrer les deux barres";
	TITAN_PANEL_MENU_DISABLE_PUSH = "Ne pas ajuster l'\195\169cran";
	TITAN_PANEL_MENU_DISABLE_MINIMAP_PUSH = "Ne pas ajuster la minicarte";
	TITAN_PANEL_MENU_DISABLE_LOGS = "Ajuster automatiquement la fen\195\168tre de discussion";
	TITAN_PANEL_MENU_BUILTINS = "Modules Titan";
	TITAN_PANEL_MENU_LEFT_SIDE = "C\195\180t\195\169 gauche";
	TITAN_PANEL_MENU_RIGHT_SIDE = "C\195\180t\195\169 droit";
	TITAN_PANEL_MENU_LOAD_SETTINGS = "Param\195\168tres sauvegard\195\169s";
	TITAN_PANEL_MENU_DOUBLE_BAR = "Double Barre";
	TITAN_PANEL_MENU_OPTIONS = "Options";
	TITAN_PANEL_MENU_OPTIONS_PANEL = "Panneau";
	TITAN_PANEL_MENU_OPTIONS_BARS = "Barres";
	TITAN_PANEL_MENU_OPTIONS_TOOLTIPS = "Tooltips";
	TITAN_PANEL_MENU_OPTIONS_FRAMES = "Frames";
	TITAN_PANEL_MENU_OPTIONS_LDB = "Data Broker";
	TITAN_PANEL_MENU_PLUGINS = "Plug-ins";
	TITAN_PANEL_MENU_LOCK_BUTTONS = "Verrouiller les boutons";
	TITAN_PANEL_MENU_VERSION_SHOWN = "Afficher les versions";
	TITAN_PANEL_MENU_LDB_SHOWN = "Ajouter le suffixe Broker au menu";
	TITAN_PANEL_MENU_LDB_SIDE = "Plugin du c\195\180t\195\169 droit";
	TITAN_PANEL_MENU_LDB_FORCE_LAUNCHER = "Forcer les launchers du c\195\180t\195\169 droit";
	TITAN_PANEL_MENU_DISABLE_FONT = "Changement de police d\195\169sactiv\195\169";
	TITAN_PANEL_MENU_CATEGORIES = {"G\195\169n\195\169ralit\195\169s","Combat","Informations","Interface","M\195\169tiers"}
	TITAN_PANEL_MENU_TOOLTIPS_SHOWN = "Afficher les conseils";
	TITAN_PANEL_MENU_TOOLTIPS_SHOWN_IN_COMBAT = "Cacher les tooltips en combat";
	TITAN_PANEL_MENU_CASTINGBAR = "D\195\169placer la barre de sorts";
	TITAN_PANEL_MENU_RESET = "R\195\169initialiser Titan Panel";
	TITAN_PANEL_MENU_TEXTURE_SETTINGS = "Param\195\168tres du skin";
	TITAN_PANEL_MENU_SKINS = "Skins personnalis\195\169s";
	TITAN_PANEL_MENU_ENABLED = "Activ\195\169";
	TITAN_PANEL_MENU_DISABLED = "D\195\169sactiv\195\169";

	TITAN_AUTOHIDE_TOOLTIP = "Changer l'affichage auto du panneau on/off";
	TITAN_AUTOHIDE_MENU_TEXT = "Cacher auto";

	TITAN_AMMO_FORMAT = "%d";
	TITAN_AMMO_BUTTON_LABEL_AMMO = "Munitions : ";
	TITAN_AMMO_BUTTON_LABEL_THROWN = "Armes de jet : ";
	TITAN_AMMO_BUTTON_LABEL_AMMO_THROWN = "Munitions/Jet : ";
	TITAN_AMMO_TOOLTIP = "Nombre de Munitions/Armes de jet";
	TITAN_AMMO_MENU_TEXT = "Munitions/Armes de jet";
	TITAN_AMMO_THROWN_KEYWORD = "Jet";

	TITAN_BAG_FORMAT = "%d/%d";
	TITAN_BAG_BUTTON_LABEL = "Sacs : ";
	TITAN_BAG_TOOLTIP = "Utilisation des sacs";
	TITAN_BAG_TOOLTIP_HINTS = "Info : cliquer pour ouvrir tous les sacs.";
	TITAN_BAG_MENU_TEXT = "Sac";
	TITAN_BAG_MENU_SHOW_USED_SLOTS = "Montrer les emplacements utilis\195\169s";
	TITAN_BAG_MENU_SHOW_AVAILABLE_SLOTS = "Montrer les emplacements libres";
	TITAN_BAG_MENU_IGNORE_AMMO_POUCH_SLOTS = "Ignorer les emplacements des sacs de munitions";
	TITAN_BAG_MENU_IGNORE_SHARD_BAGS_SLOTS = "Ignorer les emplacements des sacs de fragments d'\195\162me";
	TITAN_BAG_MENU_IGNORE_PROF_BAGS_SLOTS = "Ignorer les emplacements des sacs sp\195\169cifiques aux m\195\169tiers";
	TITAN_BAG_AMMO_POUCH_NAMES = {"Cartouchi\195\168re","Carquois","Giberne","Munitions","Balles","Lames","Besace des Veilleurs","Feuille d'Ancien cousue de tendons"};
	TITAN_BAG_SHARD_BAG_NAMES = {"Petite bourse d'\195\162me","Bo\195\174te d'\195\162mes","Bourse d'\195\162me","Sac en gangr\195\169toffe","Ombresac d'\195\169b\195\168ne","Sac en gangr\195\169toffe du Magma"};
	TITAN_BAG_PROF_BAG_NAMES = {"Bourse enchant\195\169e en tisse-mage","Sac enchant\195\169 en \195\169toffe runique","Sacoche d'enchanteur","Grand sac d'enchantement","Sac du feu-sorcier","Bourse d'herbes","Sac d'herbes c\195\169narien","Sacoche de C\195\169narius","Lourde boîte à outils","Boîte à outils en gangrefer","Bourse de gemmes","Sac de joyaux","Sac de mineur","Sac de mineur renforc\195\169","Sacoche d'artisan du cuir","Sac des nombreuses peaux","Sac de botanique de Mycah"};	
	
	TITAN_BGMINIMAP_MENU_TEXT = "Minicarte du champ de bataille"
	TITAN_BGMINIMAP_TOOLTIP = "Afficher/Cacher la minicarte du champ de bataille"

	TITAN_CLOCK_TOOLTIP = "Horloge";
	TITAN_CLOCK_TOOLTIP_VALUE = "D\195\169calage horaire : ";
	TITAN_CLOCK_TOOLTIP_HINT1 = "Info : cliquer pour ajuster le d\195\169calage"
	TITAN_CLOCK_TOOLTIP_HINT2 = "horaire et le format d'heure 12/24H.";
	TITAN_CLOCK_CONTROL_TOOLTIP = "D\195\169calage horaire : ";
	TITAN_CLOCK_CONTROL_TITLE = "D\195\169calage";
	TITAN_CLOCK_CONTROL_HIGH = "+12";
	TITAN_CLOCK_CONTROL_LOW = "-12";
	TITAN_CLOCK_CHECKBUTTON = "  24h";
	TITAN_CLOCK_CHECKBUTTON_TOOLTIP = "Changer le format de l'heure : 12/24 heures";
	TITAN_CLOCK_MENU_TEXT = "Horloge";
	TITAN_CLOCK_MENU_DISPLAY_ON_RIGHT_SIDE = "Afficher tout \195\160 droite";

	TITAN_COORDS_FORMAT = "(%.d, %.d)";
	TITAN_COORDS_FORMAT2 = "(%.1f, %.1f)";
	TITAN_COORDS_FORMAT3 = "(%.2f, %.2f)";
	TITAN_COORDS_FORMAT_LABEL = "(xx , yy)";
	TITAN_COORDS_FORMAT2_LABEL = "(xx.x , yy.y)";
	TITAN_COORDS_FORMAT3_LABEL = "(xx.xx , yy.yy)";
	TITAN_COORDS_FORMAT_COORD_LABEL = "Format des coordonn\195\169es";
	TITAN_COORDS_BUTTON_LABEL = "Pos. : ";
	TITAN_COORDS_TOOLTIP = "Info de position";
	TITAN_COORDS_TOOLTIP_HINTS_1 = "Astuce : shift + clic pour ajouter";
	TITAN_COORDS_TOOLTIP_HINTS_2 = "l'info de position dans les dialogues.";
	TITAN_COORDS_TOOLTIP_ZONE = "Zone : ";
	TITAN_COORDS_TOOLTIP_SUBZONE = "Sous Zone : ";
	TITAN_COORDS_TOOLTIP_PVPINFO = "Info JCJ : ";
	TITAN_COORDS_TOOLTIP_HOMELOCATION = "Position du foyer";
	TITAN_COORDS_TOOLTIP_INN = "Auberge : ";
	TITAN_COORDS_MENU_TEXT = "Position";
	TITAN_COORDS_MENU_SHOW_ZONE_ON_PANEL_TEXT = "Montrer le texte de la zone";
	TITAN_COORDS_MENU_SHOW_COORDS_ON_MAP_TEXT = "Montrer les coordonn\195\169es sur la carte du monde";
	TITAN_COORDS_MAP_COORDS_TEXT = "%d, %d";
	TITAN_COORDS_MAP_CURSOR_COORDS_TEXT = "Curseur(X,Y) : %s";
	TITAN_COORDS_MAP_PLAYER_COORDS_TEXT = "Joueur(X,Y) : %s";

	TITAN_FPS_FORMAT = "%.1f";
	TITAN_FPS_BUTTON_LABEL = "IPS : ";
	TITAN_FPS_MENU_TEXT = "IPS";
	TITAN_FPS_TOOLTIP_CURRENT_FPS = "IPS actuel : ";
	TITAN_FPS_TOOLTIP_AVG_FPS = "IPS moyen : ";
	TITAN_FPS_TOOLTIP_MIN_FPS = "IPS minimum : ";
	TITAN_FPS_TOOLTIP_MAX_FPS = "IPS maximum : ";
	TITAN_FPS_TOOLTIP = "Images par seconde";

	TITAN_LATENCY_FORMAT = "%d"..TITAN_MILLISECOND;
	TITAN_LATENCY_BANDWIDTH_FORMAT = "%.3f "..TITAN_KILOBYTES_PER_SECOND;
	TITAN_LATENCY_BUTTON_LABEL = "Latence : ";
	TITAN_LATENCY_TOOLTIP = "Etat du r\195\169seau";
	TITAN_LATENCY_TOOLTIP_LATENCY = "Latence : ";
	TITAN_LATENCY_TOOLTIP_BANDWIDTH_IN = "Bande passante sortante : ";
	TITAN_LATENCY_TOOLTIP_BANDWIDTH_OUT = "Bande passante entrante : ";
	TITAN_LATENCY_MENU_TEXT = "Latence";

	TITAN_LOOTTYPE_BUTTON_LABEL = "Butin : ";
	TITAN_LOOTTYPE_FREE_FOR_ALL = "Acc\195\168s libre";
	TITAN_LOOTTYPE_ROUND_ROBIN = "Chacun son tour";
	TITAN_LOOTTYPE_MASTER_LOOTER = "Responsable du butin";
	TITAN_LOOTTYPE_GROUP_LOOT = "Butin de groupe";
	TITAN_LOOTTYPE_NEED_BEFORE_GREED = "Le Besoin avant la Cupidit\195\169";
	TITAN_LOOTTYPE_TOOLTIP = "Type de butin";
	TITAN_LOOTTYPE_MENU_TEXT = "Type de butin";
	TITAN_LOOTTYPE_RANDOM_ROLL_LABEL = "Lancer les d\195\169s";
	TITAN_LOOTTYPE_TOOLTIP_HINT1 = "Astuce : clic pour un jet de d\195\169s.";
	TITAN_LOOTTYPE_TOOLTIP_HINT2 = "S\195\169lectionnez la plage du lancer de d\195\169s via le clic droit.";

	TITAN_MEMORY_FORMAT = "%.3f"..TITAN_MEGABYTE;
	TITAN_MEMORY_RATE_FORMAT = "%.3f"..TITAN_KILOBYTES_PER_SECOND;
	TITAN_MEMORY_BUTTON_LABEL = "M\195\169moire : ";
	TITAN_MEMORY_TOOLTIP = "Utilisation m\195\169moire";
	TITAN_MEMORY_TOOLTIP_CURRENT_MEMORY = "Actuel : ";
	TITAN_MEMORY_TOOLTIP_INITIAL_MEMORY = "Initial : ";
	TITAN_MEMORY_TOOLTIP_INCREASING_RATE = "Taux d'augmentation : ";
	TITAN_MEMORY_TOOLTIP_GC_INFO = "Info Garbage-Collection : ";
	TITAN_MEMORY_TOOLTIP_GC_THRESHOLD = "Limite du GC : ";
	TITAN_MEMORY_TOOLTIP_TIME_TO_GC = "Temps jusqu'au prochain GC : "
	TITAN_MEMORY_MENU_TEXT = "M\195\169moire";
	TITAN_MEMORY_MENU_RESET_SESSION = "R\195\169initialise les donn\195\169es";

	TITAN_MONEY_GOLD = "o";
	TITAN_MONEY_SILVER = "a";
	TITAN_MONEY_COPPER = "c";
	TITAN_MONEY_FORMAT = "%d"..TITAN_MONEY_GOLD..", %d"..TITAN_MONEY_SILVER..", %d"..TITAN_MONEY_COPPER;

	TITAN_PERFORMANCE_TOOLTIP = "Performances";
	TITAN_PERFORMANCE_MENU_TEXT = "Performances";
	TITAN_PERFORMANCE_ADDONS = "Utilisation des addons";
	TITAN_PERFORMANCE_ADDON_MEM_USAGE_LABEL = "Utilisation m\195\169moire des addons";
	TITAN_PERFORMANCE_ADDON_CPU_USAGE_LABEL = "Utilisation CPU des addons";
	TITAN_PERFORMANCE_ADDON_NAME_LABEL = "Nom:";
	TITAN_PERFORMANCE_ADDON_USAGE_LABEL = "Utilisation";
	TITAN_PERFORMANCE_ADDON_RATE_LABEL = "Taux";
	TITAN_PERFORMANCE_ADDON_TOTAL_MEM_USAGE_LABEL = "M\195\169moire totale des addons :";
	TITAN_PERFORMANCE_ADDON_TOTAL_CPU_USAGE_LABEL = "Temps total CPU :";
	TITAN_PERFORMANCE_MENU_SHOW_FPS = "Montrer les IPS";
	TITAN_PERFORMANCE_MENU_SHOW_LATENCY = "Montrer la latence";
	TITAN_PERFORMANCE_MENU_SHOW_MEMORY = "Montrer la m\195\169moire";
	TITAN_PERFORMANCE_MENU_SHOW_ADDONS = "Montrer l'utilisation m\195\169moire/CPU des addons";
	TITAN_PERFORMANCE_MENU_SHOW_ADDON_RATE = "Afficher le taux d'occupation m\195\169moire/CPU";
	TITAN_PERFORMANCE_MENU_CPUPROF_LABEL = "Analyse de performances CPU ";
	TITAN_PERFORMANCE_MENU_CPUPROF_LABEL_ON = "Activer l'analyse CPU ";
	TITAN_PERFORMANCE_MENU_CPUPROF_LABEL_OFF = "D\195\169sactiver l'analyse CPU ";
	TITAN_PERFORMANCE_CONTROL_TOOLTIP = "Addons surveill\195\169s : ";
	TITAN_PERFORMANCE_CONTROL_TITLE = "Addons \195\160 surveiller";
	TITAN_PERFORMANCE_CONTROL_HIGH = "40";
	TITAN_PERFORMANCE_CONTROL_LOW = "1";
	TITAN_PERFORMANCE_TOOLTIP_HINT = "Astuce : clic pour forcer un garbage collection.";

	TITAN_RIDER_HINT = "Vous \195\170tes actuelement ";
	TITAN_RIDER_OPTIONS_SHOWSTATE = "Afficher l'\195\169tat du joueur";
	TITAN_RIDER_OPTIONS_DISMOUNTDELAY = "D\195\169lai de changement d'\195\169quipement";
	TITAN_RIDER_OPTIONS_EQUIP = "Equiper les objets";
	TITAN_RIDER_STATES = {"\195\160 pied", "en monture", "en vol", "en taxi", "en nage", "m\195\169tamorphos\195\169"};
	TITAN_RIDER_ITEMS = 6;
	TITAN_RIDER_ITEMS_LABEL = "Objets pour la monture";
	TITAN_RIDER_ITEM_NAMES = {"Bottes avec les \195\169perons de mithril","Gants avec l'enchantement d'\195\169quitation","Carotte et b\195\162ton","Cravache d'\195\169quitation","Fouet de brise-ciel","Charme du vol rapide"};
	TITAN_RIDER_ITEM_DESCS = {"+4%% \195\160 la vitesse de la monture","+2%% \195\160 la vitesse de la monture","Carotte et b\195\162ton","Cravache d'\195\169quitation","Fouet de brise-ciel","Charme du vol rapide"};
	TITAN_RIDER_ITEM_SLOTS = {"FeetSlot","HandsSlot","Trinket0Slot","Trinket0Slot","Trinket0Slot","Trinket0Slot"};
	TITAN_RIDER_DRUID_FLIGHT_FORM = "Forme de vol";
	TITAN_RIDER_DRUID_SWIFTFLIGHT_FORM = "Forme de vol rapide";

	TITAN_TRANS_TOOLTIP = "Contr\195\180le de la transparence";
	TITAN_TRANS_TOOLTIP_VALUE = "Opacit\195\169 de la barre principale : ";
	TITAN_AUXTRANS_TOOLTIP_VALUE = "Opacit\195\169 de la barre secondaire : ";
	TITAN_TRANS_TOOLTIP_HINT1 = "Info : clic pour ajuster";
	TITAN_TRANS_TOOLTIP_HINT2 = "l'opacit\195\169 du panneau.";
	TITAN_TRANS_CONTROL_TOOLTIP = "Opacit\195\169 de la barre principale : ";
	TITAN_AUXTRANS_CONTROL_TOOLTIP = "Opacit\195\169 de la barre secondaire : ";
	TITAN_TRANS_MAIN_CONTROL_TITLE = "Principale";
	TITAN_TRANS_AUX_CONTROL_TITLE = "Secondaire";
	TITAN_TRANS_CONTROL_HIGH = "100%";
	TITAN_TRANS_CONTROL_LOW = "0%";
	TITAN_TRANS_MENU_TEXT = "Opacit\195\169 des barres";

	TITAN_UISCALE_TOOLTIP = "Echelle Interface/Panneau/Police";
	TITAN_UISCALE_TOOLTIP_VALUE_UI = "Echelle Interface : ";
	TITAN_UISCALE_TOOLTIP_VALUE_PANEL = "Echelle Panneau : ";
	TITAN_UISCALE_TOOLTIP_VALUE_BUTTON = "Espacement des boutons : ";
	TITAN_UISCALE_TOOLTIP_VALUE_TOOLTIPTRANS = "Transparence des tooltips : ";
	TITAN_UISCALE_TOOLTIP_VALUE_TOOLTIPFONT = "Echelle de la police des tooltips : ";
	TITAN_UISCALE_TOOLTIP_DISABLE_TEXT = "D\195\169sactiver ces r\195\169glages";
	TITAN_UISCALE_TOOLTIP_DISABLE_TOOLTIP = "D\195\169sactiver ces r\195\169glages sp\195\169cifiques des tooltips et boutons de Titan Panel";
	TITAN_UISCALE_TOOLTIP_HINT1 = "Info : clic pour ajuster la taille";
	TITAN_UISCALE_TOOLTIP_HINT2 = "du panneau ou de l'interface joueur du jeu.";
	TITAN_UISCALE_CONTROL_TOOLTIP_UI = "Echelle Interface : ";
	TITAN_UISCALE_CONTROL_TOOLTIP_PANEL = "Echelle Panneau : ";
	TITAN_UISCALE_CONTROL_TOOLTIP_BUTTON = "Espacement des boutons : ";
	TITAN_UISCALE_CONTROL_TOOLTIP_TOOLTIPTRANS = "Transparence des tooltips : ";
	TITAN_UISCALE_CONTROL_TOOLTIP_TOOLTIPFONT = "Echelle de la police des tooltips : ";
	TITAN_UISCALE_CONTROL_TITLE_UI = "Echelle\nInterface";
	TITAN_UISCALE_CONTROL_TITLE_PANEL = "Panneau";
	TITAN_UISCALE_CONTROL_TITLE_BUTTON = "Espacement\n des boutons";
	TITAN_UISCALE_CONTROL_TITLE_TOOLTIPTRANS = "Transparence\n des tooltips";
	TITAN_UISCALE_CONTROL_TITLE_TOOLTIPFONT = "Police\n des tooltips";
	TITAN_UISCALE_CONTROL_HIGH_UI = "100%";
	TITAN_UISCALE_CONTROL_HIGH_PANEL = "125%";
	TITAN_UISCALE_CONTROL_HIGH_BUTTON = "100%";
	TITAN_UISCALE_CONTROL_HIGH_TOOLTIPTRANS = "100%";
	TITAN_UISCALE_CONTROL_HIGH_TOOLTIPFONT = "130%";
	TITAN_UISCALE_CONTROL_LOW_UI = "64%";
	TITAN_UISCALE_CONTROL_LOW_PANEL = "75%";
	TITAN_UISCALE_CONTROL_LOW_BUTTON = "6%";
	TITAN_UISCALE_CONTROL_LOW_TOOLTIPTRANS = "0%";
	TITAN_UISCALE_CONTROL_LOW_TOOLTIPFONT = "50%";
	TITAN_UISCALE_MENU_TEXT = "Echelle Interface/Panneau/Police";

	TITAN_VOLUME_TOOLTIP = "Contr\195\180le du volume";
	TITAN_VOLUME_MASTER_TOOLTIP_VALUE = "Volume global : ";
	TITAN_VOLUME_SOUND_TOOLTIP_VALUE = "Volume des effets : ";
	TITAN_VOLUME_AMBIENCE_TOOLTIP_VALUE = "Volume de l'ambiance : ";
	TITAN_VOLUME_MUSIC_TOOLTIP_VALUE = "Volume de la musique : ";
	TITAN_VOLUME_MICROPHONE_TOOLTIP_VALUE = "Volume du microphone : ";
	TITAN_VOLUME_SPEAKER_TOOLTIP_VALUE = "Volume des voix : ";
	TITAN_VOLUME_TOOLTIP_HINT1 = "Info : clic pour ajuster"
	TITAN_VOLUME_TOOLTIP_HINT2 = "le volume sonore.";
	TITAN_VOLUME_CONTROL_TOOLTIP = "Volume : ";
	TITAN_VOLUME_CONTROL_TITLE = "Volume";
	TITAN_VOLUME_MASTER_CONTROL_TITLE = "Global";
	TITAN_VOLUME_SOUND_CONTROL_TITLE = "Effets";
	TITAN_VOLUME_AMBIENCE_CONTROL_TITLE = "Ambiance";
	TITAN_VOLUME_MUSIC_CONTROL_TITLE = "Musique";
	TITAN_VOLUME_MICROPHONE_CONTROL_TITLE = "Micro";
	TITAN_VOLUME_SPEAKER_CONTROL_TITLE = "Voix";
	TITAN_VOLUME_CONTROL_HIGH = "Haut";
	TITAN_VOLUME_CONTROL_LOW = "Bas";
	TITAN_VOLUME_MENU_TEXT = "Ajustement du volume";

	TITAN_XP_FORMAT = "%d";
	TITAN_XP_PERCENT_FORMAT = TITAN_XP_FORMAT.." (%.1f%%)";
	TITAN_XP_BUTTON_LABEL_XPHR_LEVEL = "XP/hr pour ce level : ";
	TITAN_XP_BUTTON_LABEL_XPHR_SESSION = "XP/hr pour cette session : ";
	TITAN_XP_BUTTON_LABEL_TOLEVEL_TIME_LEVEL = "Temps avant level : ";
	TITAN_XP_BUTTON_LABEL_TOLEVEL_TIME_SESSION = "Temps avant level : ";
	TITAN_XP_TOOLTIP = "Info XP";
	TITAN_XP_TOOLTIP_TOTAL_TIME = "Temps de jeu total : ";
	TITAN_XP_TOOLTIP_LEVEL_TIME = "Temps jou\195\169 pour ce level : ";
	TITAN_XP_TOOLTIP_SESSION_TIME = "Temps jou\195\169 pour cette session : ";
	TITAN_XP_TOOLTIP_TOTAL_XP = "XP Total requis pour ce level : ";
	TITAN_XP_TOOLTIP_LEVEL_XP = "XP gagn\195\169 pour ce level : ";
	TITAN_XP_TOOLTIP_TOLEVEL_XP = "XP n\195\169cessaire pour ce level : ";
	TITAN_XP_TOOLTIP_SESSION_XP = "XP gagn\195\169 pour cette session : ";
	TITAN_XP_TOOLTIP_XPHR_LEVEL = "XP/hr pour ce level : ";
	TITAN_XP_TOOLTIP_XPHR_SESSION = "XP/hr pour cette session : ";
	TITAN_XP_TOOLTIP_TOLEVEL_LEVEL = "Temps avant level (taux level) : ";
	TITAN_XP_TOOLTIP_TOLEVEL_SESSION = "Temps avant level (taux session) : ";
	TITAN_XP_MENU_TEXT = "XP";
	TITAN_XP_MENU_SHOW_XPHR_THIS_LEVEL = "Montrer XP/hr pour ce level";
	TITAN_XP_MENU_SHOW_XPHR_THIS_SESSION = "Montrer XP/hr pour cette session";
	TITAN_XP_MENU_RESET_SESSION = "R\195\169initialise la session";
	TITAN_XP_MENU_REFRESH_PLAYED = "Rafra\195\174chir les compteurs";

	TITAN_REGEN_MENU_TEXT 		= "Regen"
	TITAN_REGEN_MENU_TOOLTIP_TITLE	= "Taux de regen"
	TITAN_REGEN_MENU_SHOW1 		= "Exposition"
	TITAN_REGEN_MENU_SHOW2 		= "Sant\195\169 (HP)"
	TITAN_REGEN_MENU_SHOW3 		= "Mana (MP)"
	TITAN_REGEN_MENU_SHOW4		= "Double d\195\169cimale"
	TITAN_REGEN_BUTTON_TEXT_HP 		= "HP: "..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_BUTTON_TEXT_HP_PERCENT 	= "HP: "..HIGHLIGHT_FONT_COLOR_CODE.."%.2f"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_BUTTON_TEXT_MP 		= " MP: "..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_BUTTON_TEXT_MP_PERCENT 	= " MP: "..HIGHLIGHT_FONT_COLOR_CODE.."%.2f"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP1 		= "Sant\195\169 (HP): \t"..GREEN_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." / " ..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." ("..RED_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE..")";
	TITAN_REGEN_TOOLTIP2 		= "Mana (MP): \t"..GREEN_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." / " ..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." ("..RED_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE..")";
	TITAN_REGEN_TOOLTIP3 		= "Meilleur Regen HP: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP4 		= "Plus mauvais Regen HP: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP5 		= "Meilleur Regen MP: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP6 		= "Plus mauvais Regen MP: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP7		= "Regen MP du dernier combat: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." ("..GREEN_FONT_COLOR_CODE.."%.2f"..FONT_COLOR_CODE_CLOSE.."%%)";

	TITAN_ITEMBONUSES_TEXT = "Bonus Objets";
	TITAN_ITEMBONUSES_DISPLAY_NONE = "Afficher aucun";
	TITAN_ITEMBONUSES_SHORTDISPLAY = "Label bref";
	TITAN_ITEMBONUSES_BONUSSCANNER_MISSING = "L'addon BonusScanner est requis";

	TITAN_ITEMBONUSES_CAT_ATT = "Attributs";
	TITAN_ITEMBONUSES_CAT_RES = "R\195\169sistances";
	TITAN_ITEMBONUSES_CAT_SKILL = "Talents";
	TITAN_ITEMBONUSES_CAT_BON = "Combat";
	TITAN_ITEMBONUSES_CAT_SBON = "Sorts";
	TITAN_ITEMBONUSES_CAT_OBON = "Vie et mana";
	TITAN_ITEMBONUSES_CAT_EBON = "Bonus Sp\195\169ciaux";

	--Titan Repair
	REPAIR_LOCALE = {
		pattern = "^Durabilit\195\169 (%d+) / (%d+)$",
		menu = "R\195\169paration",
		tooltip = "Info de durabilit\195\169",
		button = "Durabilit\195\169: ",
		normal = "Co\195\187t de r\195\169paration (normal) : ",
		friendly = "Co\195\187t de r\195\169paration (amical) : ",
		honored = "Co\195\187t de r\195\169paration (honor\195\169) : ",
		revered = "Co\195\187t de r\195\169paration (r\195\169v\195\169r\195\169) : ",
		exalted = "Co\195\187t de r\195\169paration (exalt\195\169) : ",
		buttonNormal = "Afficher normal",
		buttonFriendly = "Afficher amical (5%)",
		buttonHonored = "Afficher honor\195\169 (10%)",
		buttonRevered = "Afficher r\195\169v\195\169r\195\169 (15%)",
		buttonExalted = "Afficher exalt\195\169 (20%)",
		percentage = "Afficher en pourcentage",
		itemname = "Afficher le nom des objets",
		undamaged = "Afficher les objets intacts",
		discount = "Afficher la r\195\169duction sur le bouton de la barre et les noms d'objets",
		nothing = "Aucun objet endommag\195\169",
		confirmation = "Voulez vous r\195\169parer tous vos objets ?",
		badmerchant = "Ce marchand ne peut pas r\195\169parer. Affichage des co\195\187ts de r\195\169paration normaux.",
		popup = "Afficher la demande de r\195\169paration",
		showinventory = "R\195\169parer aussi l'inventaire",
		WholeScanInProgress = "Mise \195\160 jour...",
		AutoReplabel = "R\195\169paration Auto",
		AutoRepitemlabel = "R\195\169paration automatique de tous les objets"
	};

	TITAN_PLUGINS_MENU_TITLE = "Plug-ins";

	CUSTOMIZATION_FEATURE_COMING_SOON = "Options de personnalisation \195\160 venir...";
end
