-- Version : Russian
-- Translated by StingerSoft (aka Eritnull)

function TitanLocalizeRU() 
	TITAN_DEBUG = "<Titan>";
	TITAN_INFO = "<Titan>"

	TITAN_NA = "N/A";
	TITAN_SECONDS = "секунды";
	TITAN_MINUTES = "минуьы";
	TITAN_HOURS = "часы";
	TITAN_DAYS = "дни";
	TITAN_SECONDS_ABBR = "с";
	TITAN_MINUTES_ABBR = "м";
	TITAN_HOURS_ABBR = "ч";
	TITAN_DAYS_ABBR = "д";
	TITAN_MILLISECOND = "мс";
	TITAN_KILOBYTES_PER_SECOND = "кб/с";
	TITAN_KILOBITS_PER_SECOND = "кбит/с"
	TITAN_MEGABYTE = "мб";
	
	TITAN_MOVABLE_TOOLTIP = "Тяните для перемещения";

	TITAN_PANEL_ERROR_DUP_PLUGIN = " возможно зарегистрирован дважды, неудается загрузить Titan panel, пожалуйста исправьте эту проблему"
	
	-- slash command help
	TITAN_PANEL_SLASH_STRING2 = LIGHTYELLOW_FONT_COLOR_CODE.."Usage: |cffffffff/tp {reset | reset tipfont/tipalpha/panelscale/spacing}";
	TITAN_PANEL_SLASH_STRING3 = " - "..LIGHTYELLOW_FONT_COLOR_CODE.."reset: |cffffffffСбрасывает все на стандартные значения/позиции.";
	TITAN_PANEL_SLASH_STRING4 = " - "..LIGHTYELLOW_FONT_COLOR_CODE.."reset tipfont: |cffffffffСбрасывает масштаб шрифта подсказки панели на стандартное значение.";
	TITAN_PANEL_SLASH_STRING5 = " - "..LIGHTYELLOW_FONT_COLOR_CODE.."reset tipalpha: |cffffffffСбрасывает прозрачность подсказки панели на стандартное значение.";
	TITAN_PANEL_SLASH_STRING6 = " - "..LIGHTYELLOW_FONT_COLOR_CODE.."reset panelscale: |cffffffffСбрасывает масштаб на стандартное значение.";
	TITAN_PANEL_SLASH_STRING7 = " - "..LIGHTYELLOW_FONT_COLOR_CODE.."reset spacing: |cffffffffСбрасывает расстояние кнопок  на стандартное значение.";
	TITAN_PANEL_SLASH_STRING8 = LIGHTYELLOW_FONT_COLOR_CODE.."Для справки по BonusScanner, введите : |cffffffff/bs"..LIGHTYELLOW_FONT_COLOR_CODE.." или |cffffffff/bscan";
	
	-- slash command responses
	TITAN_PANEL_SLASH_RESP1 = LIGHTYELLOW_FONT_COLOR_CODE.."Масштаб шрифта подсказки Titan Panel сброшен.";
	TITAN_PANEL_SLASH_RESP2 = LIGHTYELLOW_FONT_COLOR_CODE.."Прозрачность шрифта подсказки Titan Panel сброшена.";
	TITAN_PANEL_SLASH_RESP3 = LIGHTYELLOW_FONT_COLOR_CODE.."Масштаб Titan Panel сброшен.";
	TITAN_PANEL_SLASH_RESP4 = LIGHTYELLOW_FONT_COLOR_CODE.."Расстояние кнопок Titan Panel сброшено.";
	
	TITAN_PANEL = "Титан панель";
	TITAN_PANEL_VERSION_INFO = "|cffffffff by the |cffff8c00Titan Dev Team".." |cffffffff(HonorGoG, joejanko, Lothayer, Tristanian, oXidFoX, urnati & StingerSoft)";
	TITAN_PANEL_MENU_TITLE = "Титан панель";
	TITAN_PANEL_MENU_HIDE = "Скрыть";
	TITAN_PANEL_MENU_CUSTOMIZE = "Настроить";
	TITAN_PANEL_MENU_IN_COMBAT_LOCKDOWN = "(В Бою)";
	TITAN_PANEL_MENU_RELOADUI = "(Перезагрузить ПИ)";
	TITAN_PANEL_MENU_SHOW_COLORED_TEXT = "Показывать цветной текст";
	TITAN_PANEL_MENU_SHOW_ICON = "Показывать иконку";
	TITAN_PANEL_MENU_SHOW_LABEL_TEXT = "Текст ярлыка";
	TITAN_PANEL_MENU_AUTOHIDE = "Авто-скрытие";
	TITAN_PANEL_MENU_BGMINIMAP = "Мини-карта ПС";
	TITAN_PANEL_MENU_CENTER_TEXT = "Текст в центре";
	TITAN_PANEL_MENU_DISPLAY_ONTOP = "Показывать верх";
	TITAN_PANEL_MENU_DISPLAY_BOTH = "Показывать обе полосы";
	TITAN_PANEL_MENU_DISABLE_PUSH = "Выключить подстройку экрана";
	TITAN_PANEL_MENU_DISABLE_MINIMAP_PUSH = "Отключить подстройку мини-карты";
	TITAN_PANEL_MENU_DISABLE_LOGS = "Авто подстройка записи";
	TITAN_PANEL_MENU_BUILTINS = "Сборки титана";
	TITAN_PANEL_MENU_LEFT_SIDE = "Левая сторона";
	TITAN_PANEL_MENU_RIGHT_SIDE = "Правая сторона";
	TITAN_PANEL_MENU_LOAD_SETTINGS = "Загрузить настройки";
	TITAN_PANEL_MENU_DOUBLE_BAR = "Двойные полосы";
	TITAN_PANEL_MENU_OPTIONS = "Опции";
	TITAN_PANEL_MENU_OPTIONS_PANEL = "Панель";
	TITAN_PANEL_MENU_OPTIONS_BARS = "Полосы";
	TITAN_PANEL_MENU_OPTIONS_TOOLTIPS = "Подсказки";
	TITAN_PANEL_MENU_OPTIONS_FRAMES = "Фреймы";
	TITAN_PANEL_MENU_OPTIONS_LDB = "Data Broker";
	TITAN_PANEL_MENU_PLUGINS = "Плагины";
	TITAN_PANEL_MENU_LOCK_BUTTONS = "Блокировать кнопки";
	TITAN_PANEL_MENU_VERSION_SHOWN = "Показывать версии плагинов";
	TITAN_PANEL_MENU_LDB_SHOWN = "Показ суффикс Broker плагина";
	TITAN_PANEL_MENU_LDB_SIDE = "Плагин справа";
	TITAN_PANEL_MENU_LDB_FORCE_LAUNCHER = "Направить модуля запусков в правую сторону";
	TITAN_PANEL_MENU_DISABLE_FONT = "Выключить масштабирование шрифтов";
	TITAN_PANEL_MENU_CATEGORIES = {"Главная","Бой","Информация","Интерфейс","Профессия"}
	TITAN_PANEL_MENU_TOOLTIPS_SHOWN = "Показывать подсказки";
	TITAN_PANEL_MENU_TOOLTIPS_SHOWN_IN_COMBAT = "Скрыть подсказки в бою";
	TITAN_PANEL_MENU_CASTINGBAR = "Двигать полосу применения заклинания";
	TITAN_PANEL_MENU_RESET = "Сброс панели на стандарт";
	TITAN_PANEL_MENU_TEXTURE_SETTINGS = "Настройки шкурки";
	TITAN_PANEL_MENU_SKINS = "Пользовательская шкурка";
	TITAN_PANEL_MENU_ENABLED = "Включен";
	TITAN_PANEL_MENU_DISABLED = "Отключен";
	
	TITAN_AUTOHIDE_TOOLTIP = "Авто-скрытие панели вкл/выкл";
	TITAN_AUTOHIDE_MENU_TEXT = "Авто-скрытие";
	
	TITAN_AMMO_FORMAT = "%d";
	TITAN_AMMO_BUTTON_LABEL_AMMO = "Боеприпасы: ";
	TITAN_AMMO_BUTTON_LABEL_THROWN = "Бросок: ";
	TITAN_AMMO_BUTTON_LABEL_AMMO_THROWN = "Ammo/Бросок: ";
	TITAN_AMMO_TOOLTIP = "Число доступных Боеприпасов/Бросков";
	TITAN_AMMO_MENU_TEXT = "Боеприпасы/Броски";
	TITAN_AMMO_THROWN_KEYWORD = "Бросок";
	
	TITAN_BAG_FORMAT = "%d/%d";
	TITAN_BAG_BUTTON_LABEL = "Сумки: ";
	TITAN_BAG_TOOLTIP = "Использование сумок";
	TITAN_BAG_TOOLTIP_HINTS = "ЛКМ -открыть все сумки";
	TITAN_BAG_MENU_TEXT = "Сумки";
	TITAN_BAG_MENU_SHOW_USED_SLOTS = "Показывать исп. сумки";
	TITAN_BAG_MENU_SHOW_AVAILABLE_SLOTS = "Показывать доступные слоты";
	TITAN_BAG_MENU_IGNORE_AMMO_POUCH_SLOTS = "Игнорорировать Подсумок";
	TITAN_BAG_MENU_IGNORE_SHARD_BAGS_SLOTS = "Игнорорировать сумки осколков";
	TITAN_BAG_MENU_IGNORE_PROF_BAGS_SLOTS = "Игнорорировать сумки для профф";
	TITAN_BAG_SHARD_BAG_NAMES = {"душ", "Сумка из ткани Скверны", " Сумка из сердцевинной ткани Скверны", "Черная сумка теней", "сумка теней"};
	TITAN_BAG_AMMO_POUCH_NAMES = {"Подсумок", "Колчан", "патронташ", "Shot", "ламина"};
	TITAN_BAG_PROF_BAG_NAMES = {"Зачарованный мешочек из магической ткани","Зачарованная сумка из рунной ткани","Большая сумка наложения чар","Сумка зачаровывателя","Сумка из чароткани","Кориевый ящик с инструментами","Ящик для инструментов из оскверненного железа","Тяжелый ящик с инструментами","Мешочек для самоцветов","Сумка для драгоценностей"," Укрепленная шахтерская сумка","Шахтерский мешок","Сумка кожевника","Сумка Многих шкур","Мешочек для трав","Сумка для трав Ценариона","Сумка для книг Кенариуса"};

	TITAN_BGMINIMAP_MENU_TEXT = "Мини-карта Поля Сражения"
	TITAN_BGMINIMAP_TOOLTIP = "Переключение мини-карты полей сражений."
	
	TITAN_CLOCK_TOOLTIP = "Часы";
	TITAN_CLOCK_TOOLTIP_VALUE = "Часовое смещение: ";
	TITAN_CLOCK_TOOLTIP_HINT1 = "ЛКМ для настройки разницы с ОФФ"
	TITAN_CLOCK_TOOLTIP_HINT2 = "12/24 ч формат";
	TITAN_CLOCK_CONTROL_TOOLTIP = "Часовое смещение: ";
	TITAN_CLOCK_CONTROL_TITLE = "Смещение";
	TITAN_CLOCK_CONTROL_HIGH = "+12";
	TITAN_CLOCK_CONTROL_LOW = "-12";
	TITAN_CLOCK_CHECKBUTTON = "Фрмт 24ч";
	TITAN_CLOCK_CHECKBUTTON_TOOLTIP = "Преключение между отображением времени в 12-часовым и 24-часовым форматом";
	TITAN_CLOCK_MENU_TEXT = "Часы";
	TITAN_CLOCK_MENU_DISPLAY_ON_RIGHT_SIDE = "Отображать часы справа";
	
	TITAN_COORDS_FORMAT = "(%.d, %.d)";
	TITAN_COORDS_FORMAT2 = "(%.1f, %.1f)";
	TITAN_COORDS_FORMAT3 = "(%.2f, %.2f)";
	TITAN_COORDS_FORMAT_LABEL = "(xx , yy)";
	TITAN_COORDS_FORMAT2_LABEL = "(xx.x , yy.y)";
	TITAN_COORDS_FORMAT3_LABEL = "(xx.xx , yy.yy)";
	TITAN_COORDS_FORMAT_COORD_LABEL = "Формат координат";
	TITAN_COORDS_BUTTON_LABEL = "Место: ";
	TITAN_COORDS_TOOLTIP = "Информация о локации";
	TITAN_COORDS_TOOLTIP_HINTS_1 = "Shift + ЛКМ для добавления информации";
	TITAN_COORDS_TOOLTIP_HINTS_2 = "локации в чат";
	TITAN_COORDS_TOOLTIP_ZONE = "Зона: ";
	TITAN_COORDS_TOOLTIP_SUBZONE = "Подзона: ";
	TITAN_COORDS_TOOLTIP_PVPINFO = "PVP инфо: ";
	TITAN_COORDS_TOOLTIP_HOMELOCATION = "Место дома";
	TITAN_COORDS_TOOLTIP_INN = "Дом: ";
	TITAN_COORDS_MENU_TEXT = "Координаты";
	TITAN_COORDS_MENU_SHOW_ZONE_ON_PANEL_TEXT = "Показывать зону";
	TITAN_COORDS_MENU_SHOW_COORDS_ON_MAP_TEXT = "Показывать координаты на мировой карте";
	TITAN_COORDS_MAP_COORDS_TEXT = "%d, %d";
	TITAN_COORDS_MAP_CURSOR_COORDS_TEXT = "Курсор(X,Y): %s";
	TITAN_COORDS_MAP_PLAYER_COORDS_TEXT = "Игрок(X,Y): %s";
	
	TITAN_FPS_FORMAT = "%.1f";
	TITAN_FPS_BUTTON_LABEL = "FPS: ";
	TITAN_FPS_MENU_TEXT = "FPS";
	TITAN_FPS_TOOLTIP_CURRENT_FPS = "Текущий FPS: ";
	TITAN_FPS_TOOLTIP_AVG_FPS = "Средний FPS: ";
	TITAN_FPS_TOOLTIP_MIN_FPS = "Мин. FPS: ";
	TITAN_FPS_TOOLTIP_MAX_FPS = "Макс. FPS: ";
	TITAN_FPS_TOOLTIP = "Кадров в секунду";
	
	TITAN_LATENCY_FORMAT = "%d"..TITAN_MILLISECOND;
	TITAN_LATENCY_BANDWIDTH_FORMAT = "%.3f "..TITAN_KILOBYTES_PER_SECOND;
	TITAN_LATENCY_BUTTON_LABEL = "Пинг: ";
	TITAN_LATENCY_TOOLTIP = "Статус сети";
	TITAN_LATENCY_TOOLTIP_LATENCY = "Пинг: ";
	TITAN_LATENCY_TOOLTIP_BANDWIDTH_IN = "Вход пропуск.способность: ";
	TITAN_LATENCY_TOOLTIP_BANDWIDTH_OUT = "Выход пропуск.способность: ";
	TITAN_LATENCY_MENU_TEXT = "Пинг";
	
	TITAN_LOOTTYPE_BUTTON_LABEL = "Добыча: ";
	TITAN_LOOTTYPE_FREE_FOR_ALL = "Свободный для всех";
	TITAN_LOOTTYPE_ROUND_ROBIN = "Round robin";
	TITAN_LOOTTYPE_MASTER_LOOTER = "Мастер лут";
	TITAN_LOOTTYPE_GROUP_LOOT = "Групповой лут";
	TITAN_LOOTTYPE_NEED_BEFORE_GREED = "'Нужно' перед 'Не откажусь'";
	TITAN_LOOTTYPE_TOOLTIP = "Инфо о Типе добычи";
	TITAN_LOOTTYPE_MENU_TEXT = "Тип добычи";
	TITAN_LOOTTYPE_RANDOM_ROLL_LABEL = "Случайный ролл";
	TITAN_LOOTTYPE_TOOLTIP_HINT1 = "Совет: ЛКМ для случайного рола.";
	TITAN_LOOTTYPE_TOOLTIP_HINT2 = "ПКМ: Выберите тип ролла из меню.";
	
	TITAN_MEMORY_FORMAT = "%.3f"..TITAN_MEGABYTE;
	TITAN_MEMORY_RATE_FORMAT = "%.3f"..TITAN_KILOBYTES_PER_SECOND;
	TITAN_MEMORY_BUTTON_LABEL = "Память: ";
	TITAN_MEMORY_TOOLTIP = "Использование памяти";
	TITAN_MEMORY_TOOLTIP_CURRENT_MEMORY = "Текущая: ";
	TITAN_MEMORY_TOOLTIP_INITIAL_MEMORY = "Исходная: ";
	TITAN_MEMORY_TOOLTIP_INCREASING_RATE = "Темп прироста: ";
	TITAN_MEMORY_TOOLTIP_GC_INFO = "Чистка памяти - инфо: ";
	TITAN_MEMORY_TOOLTIP_GC_THRESHOLD = "Порог ЧП: ";
	TITAN_MEMORY_TOOLTIP_TIME_TO_GC = "Время до след ЧП: "
	TITAN_MEMORY_MENU_TEXT = "Память";
	TITAN_MEMORY_MENU_RESET_SESSION = "Сбросить данные памяти";
	
	TITAN_MONEY_GOLD = "з";
	TITAN_MONEY_SILVER = "с";
	TITAN_MONEY_COPPER = "м";
	TITAN_MONEY_FORMAT = "%d"..TITAN_MONEY_GOLD..", %d"..TITAN_MONEY_SILVER..", %d"..TITAN_MONEY_COPPER;
	
	TITAN_PERFORMANCE_TOOLTIP = "Инфо о производительности";
	TITAN_PERFORMANCE_MENU_TEXT = "Производительность";
	TITAN_PERFORMANCE_ADDONS = "Аддоны используют";
	TITAN_PERFORMANCE_ADDON_MEM_USAGE_LABEL = "Использование памети аддоном";
	TITAN_PERFORMANCE_ADDON_CPU_USAGE_LABEL = "Загрузка ЦПУ аддоном";
	TITAN_PERFORMANCE_ADDON_NAME_LABEL = "Имя:";
	TITAN_PERFORMANCE_ADDON_USAGE_LABEL = "Испл.";
	TITAN_PERFORMANCE_ADDON_RATE_LABEL = "Скорость";
	TITAN_PERFORMANCE_ADDON_TOTAL_MEM_USAGE_LABEL = "Всего памети на аддоны:";
	TITAN_PERFORMANCE_ADDON_TOTAL_CPU_USAGE_LABEL = "Всего ЦПУ:";
	TITAN_PERFORMANCE_MENU_SHOW_FPS = "Показывать FPS";
	TITAN_PERFORMANCE_MENU_SHOW_LATENCY = "Показывать пинг";
	TITAN_PERFORMANCE_MENU_SHOW_MEMORY = "Показывать память";
	TITAN_PERFORMANCE_MENU_SHOW_ADDONS = "Покапз исп. памети аддонами";
	TITAN_PERFORMANCE_MENU_SHOW_ADDON_RATE = "Показ размер исп. аддонами";
	TITAN_PERFORMANCE_MENU_CPUPROF_LABEL = "Режим анализа CPU";
	TITAN_PERFORMANCE_MENU_CPUPROF_LABEL_ON = "Включить режим анализа CPU ";
	TITAN_PERFORMANCE_MENU_CPUPROF_LABEL_OFF = "Отключить режим анализа CPU ";
	TITAN_PERFORMANCE_CONTROL_TOOLTIP = "Мониторинг Аддонов: ";
	TITAN_PERFORMANCE_CONTROL_TITLE = "Мониторинг Аддонов";
	TITAN_PERFORMANCE_CONTROL_HIGH = "40";
	TITAN_PERFORMANCE_CONTROL_LOW = "1";
	TITAN_PERFORMANCE_TOOLTIP_HINT = "Совет: ЛКМ для Чистки памяти.";

	TITAN_RIDER_HINT = "Вы уже: ";
	TITAN_RIDER_OPTIONS_SHOWSTATE = "Показывать статус игрока";
	TITAN_RIDER_OPTIONS_DISMOUNTDELAY = "Задержка слезания";
	TITAN_RIDER_OPTIONS_EQUIP = "Одетые предметы";
	TITAN_RIDER_STATES = {"Бежите", "Верхом", "Летите", "Такси", "Плывете", "За-овцован"};
	TITAN_RIDER_ITEMS = 6;
	TITAN_RIDER_ITEMS_LABEL = "Ездовые предметы";
	TITAN_RIDER_ITEM_NAMES = {"Обувь w/Мифриловые шпоры","Перчатки w/Ездовые зачарования","Морковка на палочке","Стек","Бич Небодробителя","Оберег Стремительного Полета"};
	TITAN_RIDER_ITEM_DESCS = {"+4%% скорости верховой езды","+2%% скорости верховой езды","Морковка на палочке","Стек","Бич Небодробителя","Оберег Стремительного Полета"};
	TITAN_RIDER_ITEM_SLOTS = {"FeetSlot","HandsSlot","Trinket0Slot","Trinket0Slot","Trinket0Slot","Trinket0Slot"};
	TITAN_RIDER_DRUID_FLIGHT_FORM = "Воздушный облик";
	TITAN_RIDER_DRUID_SWIFTFLIGHT_FORM = "Облик стремительной птицы";

	TITAN_TRANS_TOOLTIP = "Информация о прозрачности";
	TITAN_TRANS_TOOLTIP_VALUE = "Прозрачность панели: ";
	TITAN_AUXTRANS_TOOLTIP_VALUE = "Прозрачность вспом-ных полос: ";
	TITAN_TRANS_TOOLTIP_HINT1 = "ЛКМ чтобы настроить";
	TITAN_TRANS_TOOLTIP_HINT2 = "прзрачность панели";
	TITAN_TRANS_CONTROL_TOOLTIP = "Прозрачность панели: ";
	TITAN_AUXTRANS_CONTROL_TOOLTIP = "Прозрачность вспом-ных полос: ";
	TITAN_TRANS_MAIN_CONTROL_TITLE = "Главные\nПолосы";
	TITAN_TRANS_AUX_CONTROL_TITLE = "Вспомог-ные\nПолосы";
	TITAN_TRANS_CONTROL_HIGH = "100%";
	TITAN_TRANS_CONTROL_LOW = "0%";
	TITAN_TRANS_MENU_TEXT = "Настройка прозрачности";
	
	TITAN_UISCALE_TOOLTIP = "Информация о панеле";
	TITAN_UISCALE_TOOLTIP_VALUE_UI = "Размер интерфейса: ";
	TITAN_UISCALE_TOOLTIP_VALUE_PANEL = "Размер панели: ";
	TITAN_UISCALE_TOOLTIP_VALUE_BUTTON = "Расстояние кнопок: ";
	TITAN_UISCALE_TOOLTIP_VALUE_TOOLTIPTRANS = "Прозрачность подсказок: ";
	TITAN_UISCALE_TOOLTIP_VALUE_TOOLTIPFONT = "Размер шрифта подсказок: ";
	TITAN_UISCALE_TOOLTIP_DISABLE_TEXT = "Выкл";
	TITAN_UISCALE_TOOLTIP_DISABLE_TOOLTIP = "Отключить маштаб шрифта подсказок Titan'а";
	TITAN_UISCALE_TOOLTIP_HINT1 = "ЛКМ чтобы настроить размер";
	TITAN_UISCALE_TOOLTIP_HINT2 = "панели или интерфейса.";
	TITAN_UISCALE_CONTROL_TOOLTIP_UI = "UI размер: ";
	TITAN_UISCALE_CONTROL_TOOLTIP_PANEL = "Размер панели: ";
	TITAN_UISCALE_CONTROL_TOOLTIP_BUTTON = "Расстояние кнопок: ";
	TITAN_UISCALE_CONTROL_TOOLTIP_TOOLTIPTRANS = "Прозрачность подсказок: ";
	TITAN_UISCALE_CONTROL_TOOLTIP_TOOLTIPFONT = "Размер шрифта подсказок: ";
	TITAN_UISCALE_CONTROL_TITLE_UI = "UI размер";
	TITAN_UISCALE_CONTROL_TITLE_PANEL = "Размер панели";
	TITAN_UISCALE_CONTROL_TITLE_BUTTON = "Кнопки\nРасстояние";
	TITAN_UISCALE_CONTROL_TITLE_TOOLTIPTRANS = "Подсказка\nПрозрачность";
	TITAN_UISCALE_CONTROL_TITLE_TOOLTIPFONT = "Подсказка\nШрифт";
	TITAN_UISCALE_CONTROL_HIGH_UI = "100%";
	TITAN_UISCALE_CONTROL_HIGH_PANEL = "125%";
	TITAN_UISCALE_CONTROL_HIGH_BUTTON = "100%";
	TITAN_UISCALE_CONTROL_HIGH_TOOLTIPTRANS = "100%";
	TITAN_UISCALE_CONTROL_HIGH_TOOLTIPFONT = "130%";
	TITAN_UISCALE_CONTROL_LOW_UI = "64%";
	TITAN_UISCALE_CONTROL_LOW_PANEL = "75%";
	TITAN_UISCALE_CONTROL_LOW_BUTTON = "6%";
	TITAN_UISCALE_CONTROL_LOW_TOOLTIPTRANS = "0%";
	TITAN_UISCALE_CONTROL_LOW_TOOLTIPFONT = "50%";
	TITAN_UISCALE_MENU_TEXT = "Настройка панели";
	
	TITAN_VOLUME_TOOLTIP = "Контроль звука";
	TITAN_VOLUME_MASTER_TOOLTIP_VALUE = "Громкость общего звука: ";
	TITAN_VOLUME_SOUND_TOOLTIP_VALUE = "Громкость звуковых эффектов: ";
	TITAN_VOLUME_AMBIENCE_TOOLTIP_VALUE = "Громкость звуков окружающего мира: ";
	TITAN_VOLUME_MUSIC_TOOLTIP_VALUE = "Громкость мызыки: ";
	TITAN_VOLUME_MICROPHONE_TOOLTIP_VALUE = "Громкость микрофона: ";
	TITAN_VOLUME_SPEAKER_TOOLTIP_VALUE = "Громкость динамиков: ";
	TITAN_VOLUME_TOOLTIP_HINT1 = "ЛКМ чтобы настроить"
	TITAN_VOLUME_TOOLTIP_HINT2 = "Громкость звука";
	TITAN_VOLUME_CONTROL_TOOLTIP = "Громкость звука: ";
	TITAN_VOLUME_CONTROL_TITLE = "Громкость";
	TITAN_VOLUME_MASTER_CONTROL_TITLE = "Общий";
	TITAN_VOLUME_SOUND_CONTROL_TITLE = "Звуки";
	TITAN_VOLUME_AMBIENCE_CONTROL_TITLE = "Мир";
	TITAN_VOLUME_MUSIC_CONTROL_TITLE = "Музыка";
	TITAN_VOLUME_MICROPHONE_CONTROL_TITLE = "Микрафон";
	TITAN_VOLUME_SPEAKER_CONTROL_TITLE = "Динамик";
	TITAN_VOLUME_CONTROL_HIGH = "Макс";
	TITAN_VOLUME_CONTROL_LOW = "Мин";
	TITAN_VOLUME_MENU_TEXT = "Настройки Звука";

	TITAN_XP_FORMAT = "%d";
	TITAN_XP_PERCENT_FORMAT = TITAN_XP_FORMAT.." (%.1f%%)";
	TITAN_XP_BUTTON_LABEL_XPHR_LEVEL = "XP/ч на этом уровне: ";
	TITAN_XP_BUTTON_LABEL_XPHR_SESSION = "XP/ч за эту сессию: ";
	TITAN_XP_BUTTON_LABEL_TOLEVEL_TIME_LEVEL = "Время до уровня: ";
	TITAN_XP_BUTTON_LABEL_TOLEVEL_TIME_SESSION = "Время до уровня: ";
	TITAN_XP_TOOLTIP = "XP инф.";
	TITAN_XP_TOOLTIP_TOTAL_TIME = "Всего времени сыграно: ";
	TITAN_XP_TOOLTIP_LEVEL_TIME = "Время игры на этом уровне: ";
	TITAN_XP_TOOLTIP_SESSION_TIME = "Время сыграно за эту сессию: ";
	TITAN_XP_TOOLTIP_TOTAL_XP = "Всего XP на этот уровень: ";
	TITAN_XP_TOOLTIP_LEVEL_XP = "XP набрано на этом уровне: ";
	TITAN_XP_TOOLTIP_TOLEVEL_XP = "XP нужно для уровня: ";
	TITAN_XP_TOOLTIP_SESSION_XP = "XP набрано за эту сессию: ";
	TITAN_XP_TOOLTIP_XPHR_LEVEL = "XP/ч на этом уровне: ";
	TITAN_XP_TOOLTIP_XPHR_SESSION = "XP/ч за эту сессию: ";
	TITAN_XP_TOOLTIP_TOLEVEL_LEVEL = "Время до уровня: ";
	TITAN_XP_TOOLTIP_TOLEVEL_SESSION = "Время до уровня: ";
	TITAN_XP_MENU_TEXT = "Опыт(XP)";
	TITAN_XP_MENU_SHOW_XPHR_THIS_LEVEL = "Показывать XP/ч на этом уровне";
	TITAN_XP_MENU_SHOW_XPHR_THIS_SESSION = "Показывать XP/ч за эту сессию";
	TITAN_XP_MENU_RESET_SESSION = "Сбросить сессию";
	TITAN_XP_MENU_REFRESH_PLAYED = "Таймеры востоновления";
	
	TITAN_REGEN_MENU_TEXT 		= "Реген"
	TITAN_REGEN_MENU_TOOLTIP_TITLE	= "Реген"
	TITAN_REGEN_MENU_SHOW1 		= "Показывать"
	TITAN_REGEN_MENU_SHOW2 		= "ЗД"
	TITAN_REGEN_MENU_SHOW3 		= "МН"
	TITAN_REGEN_MENU_SHOW4		= "в процентах"
	TITAN_REGEN_BUTTON_TEXT_HP 		= "ЗД: "..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_BUTTON_TEXT_HP_PERCENT 	= "ЗД: "..HIGHLIGHT_FONT_COLOR_CODE.."%.2f"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_BUTTON_TEXT_MP 		= " МН: "..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_BUTTON_TEXT_MP_PERCENT 	= " МН: "..HIGHLIGHT_FONT_COLOR_CODE.."%.2f"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP1           = "Здоровье: \t"..GREEN_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." / " ..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." ("..RED_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE..")";
	TITAN_REGEN_TOOLTIP2           = "Мана: \t"..GREEN_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." / " ..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." ("..RED_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE..")";
	TITAN_REGEN_TOOLTIP3 		= "Лучший ЗД реген: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP4 		= "Худший ЗД реген: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP5 		= "Лучший МН реген: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP6 		= "Худший МН реген: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE;
	TITAN_REGEN_TOOLTIP7		= "МН реген в последней схватке: \t"..HIGHLIGHT_FONT_COLOR_CODE.."%d"..FONT_COLOR_CODE_CLOSE.." ("..GREEN_FONT_COLOR_CODE.."%.2f"..FONT_COLOR_CODE_CLOSE.."%%)";

	TITAN_ITEMBONUSES_TEXT = "Бонусы предметов";
	TITAN_ITEMBONUSES_DISPLAY_NONE = "Показывать отсутствие";
	TITAN_ITEMBONUSES_SHORTDISPLAY = "Сокращенный текст";
	TITAN_ITEMBONUSES_BONUSSCANNER_MISSING = "Необходим аддон BonusScanner";

	TITAN_ITEMBONUSES_CAT_ATT = "Атрибуты";
	TITAN_ITEMBONUSES_CAT_RES = "Сопротивления";
	TITAN_ITEMBONUSES_CAT_SKILL = "Навыки";
	TITAN_ITEMBONUSES_CAT_BON = "Ближний и дальний бой";
	TITAN_ITEMBONUSES_CAT_SBON = "Заклинания";
	TITAN_ITEMBONUSES_CAT_OBON = "Жизнь и мана";
	TITAN_ITEMBONUSES_CAT_EBON = "Спец бонусы";

	--Titan Repair
	REPAIR_LOCALE["pattern"] = "^Прочность: (%d+) / (%d+)$";
	REPAIR_LOCALE["menu"] = "Инф. о прочности. брони";
	REPAIR_LOCALE["tooltip"] = "Информация о прочности амуниции";
	REPAIR_LOCALE["button"] = "Прочность: ";
	REPAIR_LOCALE["normal"] = "Стоимость починки (Стандарт): ";
	REPAIR_LOCALE["friendly"] = "Стоимость починки (Дружелюбие): ";
	REPAIR_LOCALE["honored"] = "Стоимость починки (Уважение): ";
	REPAIR_LOCALE["revered"] = "Стоимость починки (Почтитение): ";
	REPAIR_LOCALE["exalted"] = "Стоимость починки (Восторг): ";
	REPAIR_LOCALE["buttonNormal"] = "Показать Стандарт";
	REPAIR_LOCALE["buttonFriendly"] = "Показать Дружелюбие (5%)";
	REPAIR_LOCALE["buttonHonored"] = "Показать Уважение (10%)";
	REPAIR_LOCALE["buttonRevered"] = "Показать Почтитение (15%)";
	REPAIR_LOCALE["buttonExalted"] = "Показать Восторг (20%)";
	REPAIR_LOCALE["percentage"] = "Показывать в процентах";
	REPAIR_LOCALE["itemname"] = "Показывать имя предмета";
	REPAIR_LOCALE["undamaged"] = "Показывать неповреждённые предметы";
	REPAIR_LOCALE["discount"] = "Скидка";
	REPAIR_LOCALE["nothing"] = "Нет поврежденных вещей.";
	REPAIR_LOCALE["confirmation"] = "Ты хочешь починить все одетые предметы?";
	REPAIR_LOCALE["badmerchant"] = "Этот торговец не может чинить. Displaying normal repair costs instead.";
	REPAIR_LOCALE["popup"] = "Показать всплывающее меню починки";
	REPAIR_LOCALE["showinventory"] = "Подсчет повреждение инвенторя";
	REPAIR_LOCALE["WholeScanInProgress"] = "Обновление...";
	REPAIR_LOCALE["AutoReplabel"] = "Авто-Починка";
	REPAIR_LOCALE["AutoRepitemlabel"] = "Авто-Починка всех предметов";

	TITAN_PLUGINS_MENU_TITLE = "Плагины";
	
	CUSTOMIZATION_FEATURE_COMING_SOON = "Customization feature coming soon...";
end
